apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature-key-kv
spec:
  validationFailureAction: Enforce
  background: true # not breaking existing deployments if any
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-image-signature-key-kv
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences: 
        - "ghcr.io/jbrejnholt/cosign-demo/*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: "azurekms://jinhong-cosign-poc-kv.vault.azure.net/cosignkey"

