apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signature-key
spec:
  validationFailureAction: Enforce
  background: true # not breaking existing deployments if any
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: verify-image-signature-key
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences: 
        - "jinbcr.azurecr.io/*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEIMe7Qm6Hm1WFY5oL9deUwhbHA+/I
                xAIjgSOPNnjU/qoxQSPg68h3EQncJxhoApStkYCqC3TlxYFWLDe642flOg==
                -----END PUBLIC KEY-----
