apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-mutate-secret
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: mutate-data
    match:
      any:
      - resources:
          names:
            - "top-secret"
          kinds:
            - Secret
          namespaces:
            - default
    mutate:
      targets:
        - apiVersion: v1
          kind: Secret
          name: top-secret
          namespace: default
      patchStrategicMerge:
        data:
          test: "test"
          base64test: "{{ base64_encode('{{ request.object.data.a }}') }}"
