extraArgs:
  - --autoUpdateWebhooks=true
  - --imagePullSecrets=regcred #TODO
  - --loggingFormat=text

envVars:
  - name: AZURE_TENANT_ID
    valueFrom:
      secretKeyRef:
        name: cosign-key-kv #TODO
        key: tenantid
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: cosign-key-kv
        key: clientid
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: cosign-key-kv
        key: clientsecret