extraArgs:
  - --autoUpdateWebhooks=true
  - --imagePullSecrets=regcred #TODO
  - --loggingFormat=text

createSelfSignedCert: true
cleanupController: 
  rbac:
    clusterRole:
      extraResources:
      - apiGroups:
        - ''
        resources:
        - pods
        verbs:
        - list
        - delete
replicaCount: 3

envVars:
  - name: AZURE_TENANT_ID
    valueFrom:
      secretKeyRef:
        name: cosign-key-kv #TODO
        key: tenantid
  - name: AZURE_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: cosign-key-kv
        key: clientid
  - name: AZURE_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: cosign-key-kv
        key: clientsecret