admissionController:
  replicas: 3
  container:
    extraArgs:
      imagePullSecrets: "regcred" #TODO
      loggingFormat: "text"
      registryCredentialHelpers: "github"
      webhookTimeout: 15

cleanupController: 
  rbac:
    clusterRole:
      extraResources:
      - apiGroups:
        - ''
        resources:
        - pods
        verbs:
        - list
        - delete
