admissionController:
  replicas: 3

cleanupController: 
  rbac:
    clusterRole:
      extraResources:
      - apiGroups:
        - ''
        resources:
        - pods
        verbs:
        - list
        - delete
