apiVersion: kyverno.io/v2alpha1
kind: ClusterCleanupPolicy
metadata:
  name: cleanup
spec:
  match:
    any:
    - resources:
        kinds:
        - Pod
  conditions:
    any:
    - key: "{{ target.metadata.ownerReferences[] || `[]` }}"
      operator: Equals
      value: []
  schedule: "0/1 * * * *"