apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy-mutate-secret-data
spec:
  rules:
    - name: add-data
      match:
        all:
        - resources:
            kinds:
            - Secret
            namespaces:
            - default
      mutate:
        targets:
        - apiVersion: v1
          kind: Secret
          name: top-secret
          namespace: "{{ request.object.metadata.namespace }}"
        patchesJson6902: |-
          - path: "/data/newKey"
            op: add
            value: "TXlOZXdTZWNyZXQK"
