apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-postgres-cluster-secrets
spec:
  rules:
  - name: sync-postgres-cluster-secret
    match:
      any:
      - resources:
          kinds:
          - acid.zalan.do/v1/postgresql
    generate:
      apiVersion: v1
      kind: Secret
      name: psql-backup-creds
      namespace: "{{request.namespace}}"
      synchronize: true
      clone:
        namespace: default
        name: psql-backup-creds
